# Generated by Django 4.1.4 on 2023-01-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.PositiveIntegerField(db_column='id_persona', primary_key=True, serialize=False)),
                ('edad', models.SmallIntegerField()),
                ('sexo', models.SmallIntegerField()),
                ('nivel_educativo', models.SmallIntegerField()),
                ('ocupacion', models.SmallIntegerField()),
                ('introvertido_extrovertido', models.SmallIntegerField()),
                ('calmado_nervioso', models.SmallIntegerField()),
                ('mas_importancia', models.SmallIntegerField()),
                ('deporte', models.SmallIntegerField()),
                ('viajar', models.SmallIntegerField()),
                ('videojuegos', models.SmallIntegerField()),
                ('leer', models.SmallIntegerField()),
                ('cine', models.SmallIntegerField()),
                ('amistad', models.SmallIntegerField()),
                ('mascotas', models.SmallIntegerField()),
                ('apariencia', models.SmallIntegerField()),
                ('salud', models.SmallIntegerField()),
                ('experimentar', models.SmallIntegerField()),
                ('hijos', models.SmallIntegerField()),
                ('musica', models.SmallIntegerField()),
                ('sueño', models.SmallIntegerField()),
            ],
        ),
    ]
